[build-system]
requires = ["setuptools>=84.0", "setuptools-scm>=10.2", "wheel>=0.48"]
build-backend = "setuptools.build_meta"

[project]
name = "marketmimic"
version = "0.2.0"
dynamic = ["readme"]
authors = [
    { name = "©2023 TAUNAIS", email = "info@taunais.com" },
]
description = "Maker Mimic is a Python library for generating synthetic financial data."
requires-python = ">=3.11"
keywords = ["common", "python", "library"]
classifiers = ["Programming Language :: Python :: 3.11"]
dependencies = [
    "tensorflow>=2.21",
    "pandas>=3.0",
    "jupyterlab>=4.6",
    "scikit-learn>=1.9",
    "matplotlib>=3.11",
    "mplfinance>=0.12.10b0",
    "tabulate>=0.10",
    "fastdtw>=0.3"
]

[tool.setuptools.dynamic]
readme = { file = ["README.md"], content-type = "text/markdown" }

[project.optional-dependencies]
tests = [
    "time-machine>=3.5",
    "coverage>=7.16"
]
extended = [
    "time-machine>=3.5"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["marketmimic*"]
